name: Windows Self-Hosted Runner Demo
run-name: snyk pipeline
on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted  # Runs on a self-hosted Windows runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PowerShell
        shell: pwsh
        run: |
          & "C:\Users\usuario\Downloads\snyk-win.exe" code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
